name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true # <-- THIS IS THE MAGIC KEY THAT FORCES GITHUB TO FETCH THE REAL BINARY

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Serves your root folder containing the HTML file

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
